### ISSUE TITLE
SHACL validator returns many errors, when validating our own example files

### ISSUE THREAD

**Issue by peterlubrich** [mobilityDCAT-AP/mobilityDCAT-AP#40]
I have tried this online SHACL validator:
https://www.itb.ec.europa.eu/shacl/any/upload

I used the [SHACL file ](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/mobilitydcat-ap_shacl_shapes.ttl), as well as the [example populations ](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html#examples)on our Respec page.

The validator returns too many errors, see validation report:
[report.pdf](https://github.com/user-attachments/files/16309365/report.pdf)

Very often, it is stating : "Property needs to have at least 1 value"

However:
Lina did already check our example files with another validator in January 24, the results then were without errors. See her validation report:
[TestingSHACL-mobilityDCAT-AP-Iteration2.pdf](https://github.com/user-attachments/files/16309421/TestingSHACL-mobilityDCAT-AP-Iteration2.pdf)

I don't understand the new error messages.
Can anyone please check what is wrong?

**Comment by marioscrock** [comment]
Hi @peterlubrich, I did the same test and I also got many errors. I do not know which tool Lina used to perform the validation. It could be because this tool automatically imports all the referenced shapes (e.g., the ones from DCAT), while the one used before checked only the shapes we defined directly. We should check the errors one by one to understand why they are thrown.

By the way I noticed other two minor issues related that should be fixed now:
- [x] Links in the Respec page were broken because the `examples `folder was not copied there (closes #39)
- [x] The original_population XML file had an error in the comment on line 104 (closing tag)
I kindly ask @Daham-Mustaf to check that everything is fine with my last commit.

**Comment by marioscrock** [comment]
To be checked considering also #36

**Comment by Daham-Mustaf** [comment]
@marioscrock  and @peterlubrich  # SHACL Validation Issue

I expect that Lina is using the [SHACL Playground](https://shacl.org/playground/) engine for validation. I have changed `sh:Class` to `sh:class` in the SHACL shapes file.

## Next Steps

I will delve deeper into SHACL to understand why we're encountering this problem. I need some time to better comprehend the constraints and improve our approach.

## To-Do

- [x] Investigate SHACL in depth
- [x] Test the modified shapes file in SHACL Playground
- [x] Document findings and any resolutions

## Notes

The change from `sh:Class` to `sh:class` might be significant as SHACL is case-sensitive. Further investigation is needed to ensure this change aligns with SHACL specifications.

**Comment by marioscrock** [comment]
@Daham-Mustaf Please perform check again against examples in the spec before release 1.1.0

**Comment by peterlubrich** [comment]
I have run the SHACL playground as follows:

- Shapes graph: [SHACL file updated for v1.1.0](https://github.com/mobilityDCAT-AP/mobilityDCAT-AP/blob/gh-pages/drafts/latest/validationFiles/mobilitydcat-ap_shacl_shapes.ttl)
- Data graph: [SE example file](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/examples/SE%20NAP_dataset_expressed%20in%20mobilityDCAT-AP_original%20population_240205.ttl)

There are no more errors, so I am closing this issue
